### ISSUE TITLE
azure-storage与azure-storage-blob冲突

### ISSUE THREAD

**Issue by sunliangtian** [Azure-Samples/azure-sdk-for-java-storage-blob-upload-download#9]
错误原因：
azure-storage-blob与azure-storage的jar包有冲突，Azure Table Storage和Azure Blob不能在同一个Project中创建，此问题导致获取blobList会导致ListBlobsOptions报java.lang.NoSuchFieldError: NONE错误。
实测10.1.0-10.3.0都包含此问题。

错误信息：
Exception in thread "main" java.lang.NoSuchFieldError: NONE
	at com.microsoft.azure.storage.blob.ListBlobsOptions.<init>(ListBlobsOptions.java:36)
	at com.microsoft.azure.storage.blob.ListBlobsOptions.<clinit>(ListBlobsOptions.java:27)
	at quickstart.Quickstart.listBlobs(Quickstart.java:67)
	at quickstart.Quickstart.main(Quickstart.java:188)

POM配置：
<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-storage</artifactId>
            <version>8.0.0</version>
        </dependency>

        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-storage-blob</artifactId>
            <version>10.3.0</version>
        </dependency>

**Comment by jongio** [comment]
This should be resolved.  Please reopen if you are able to reproduce.  Thanks
